import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryProvider } from "@/src/providers/ReactQueryProvider";
import {
    kodchasanLight,
    kodchasanRegular,
    kodchasanSemiBold,
    literataRegular,
    literataSemiBold,
} from "./fonts";

export const metadata: Metadata = {
    title: "Flo Studio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className='h-full'
        >
            <body
                className={`${kodchasanLight.variable} ${kodchasanRegular.variable} ${kodchasanSemiBold.variable} ${literataRegular.variable} ${literataSemiBold.variable} min-h-screen h-full  antialiased relative `}
            >
                <ReactQueryProvider>{children}</ReactQueryProvider>
            </body>
        </html>
    );
}
