import type { Metadata } from "next";
import "./globals.css";
import {
    kodchasanLight,
    kodchasanRegular,
    kodchasanSemiBold,
    kodchasanBold,
    literataLight,
    literataRegular,
    literataSemiBold,
    literataBold,
    literataBlack,
} from "./fonts";
import { ReactQueryProvider } from "@/src/providers/ReactQueryProvider";
import HeaderController from "@/component/Header/HeaderController";
import FooterController from "@/component/Footer/FooterController";
export const metadata: Metadata = {
    title: "Flo Studio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className='h-full'
        >
            <body
                className={`${kodchasanLight.variable} ${kodchasanRegular.variable} ${kodchasanSemiBold.variable} ${kodchasanBold.variable} ${literataLight.variable} ${literataRegular.variable} ${literataSemiBold.variable} ${literataBold.variable} ${literataBlack.variable} h-full antialiased relative `}
            >
                <ReactQueryProvider>
                    {/* <HeaderController /> */}
                    {children}
                    {/* <FooterController /> */}
                </ReactQueryProvider>
            </body>
        </html>
    );
}
